# Generated by Django 3.0.4 on 2020-03-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100, null=True)),
                ('Birth_day', models.DateField(null=True)),
                ('FB_link', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
