# Generated by Django 3.0.4 on 2020-03-16 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Creation', '0001_initial'),
        ('Authentication', '0001_initial'),
        ('Home_Page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='project_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project_Creation.Projects'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.Users'),
        ),
        migrations.AddField(
            model_name='rate',
            name='project_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project_Creation.Projects'),
        ),
        migrations.AddField(
            model_name='rate',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.Users'),
        ),
        migrations.AddField(
            model_name='report',
            name='comment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home_Page.Comments'),
        ),
        migrations.AddField(
            model_name='report',
            name='project_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project_Creation.Projects'),
        ),
        migrations.AddField(
            model_name='report',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.Users'),
        ),
    ]
