# Generated by Django 3.0.4 on 2020-03-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0003_auto_20200319_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate_value',
            field=models.DecimalField(decimal_places=11, max_digits=11),
        ),
    ]
