# Generated by Django 3.0.4 on 2020-03-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('password', models.BigIntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField()),
                ('phone', models.BigIntegerField()),
            ],
        ),
    ]
