# Generated by Django 3.0.4 on 2020-03-21 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_auto_20200321_0525'),
        ('Authentication', '0003_auto_20200321_2231'),
    ]

    operations = [
    ]
