# Generated by Django 3.0.4 on 2020-03-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Creation', '0002_auto_20200316_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='tags_id',
        ),
        migrations.AddField(
            model_name='projects',
            name='choosen_byAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
