# Generated by Django 3.0 on 2020-03-19 12:20

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('Project_Creation', '0003_auto_20200316_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='category_id',
        ),
        migrations.AddField(
            model_name='images',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Images_project', to='Project_Creation.Projects'),
        ),
        migrations.AddField(
            model_name='images',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Authentication.Users'),
        ),
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('1', 'Health'), ('2', 'Sports'), ('3', 'Innovation'), ('4', 'Creativity'), ('5', 'BLABLABLA'), ('6', 'any thing')], default='Innovation', max_length=1),
        ),
        migrations.AddField(
            model_name='projects',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(null=True, upload_to='images/projects', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='images',
            name='project_Id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Project_Creation.Projects'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='cover',
            field=models.ImageField(null=True, upload_to='images/projects', verbose_name='cover_image'),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
