# Generated by Django 3.0 on 2020-03-19 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
        ('Project_Creation', '0005_auto_20200319_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Images_project', to='Project_Creation.Projects'),
        ),
        migrations.AlterField(
            model_name='images',
            name='project_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project_Creation.Projects'),
        ),
        migrations.AlterField(
            model_name='images',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.Users'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('1', 'Health'), ('2', 'Sports'), ('3', 'Innovation'), ('4', 'Creativity'), ('5', 'BLABLABLA'), ('6', 'any thing')], max_length=1, null=True),
        ),
    ]
