# Generated by Django 3.0 on 2020-03-20 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Creation', '0006_auto_20200319_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='category',
        ),
        migrations.AddField(
            model_name='projects',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project_Creation.Category'),
        ),
    ]
