# Generated by Django 3.0.4 on 2020-03-21 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Creation', '0007_auto_20200320_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
