# Generated by Django 3.0.4 on 2020-03-16 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Creation', '0001_initial'),
        ('Authentication', '0001_initial'),
        ('Make_Donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='project_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project_Creation.Projects'),
        ),
        migrations.AddField(
            model_name='donation',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.Users'),
        ),
    ]
