# Generated by Django 3.0.4 on 2020-03-16 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_category_comments_images_projects_rate_report_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Category'),
        ),
        migrations.AddField(
            model_name='projects',
            name='image_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Images'),
        ),
        migrations.AddField(
            model_name='projects',
            name='tags_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Tags'),
        ),
    ]
