# Generated by Django 3.0.4 on 2020-03-16 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200316_1452'),
        ('projects', '0004_auto_20200316_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Users'),
        ),
    ]
